// src/utils/constants.ts
export const MOCK_API_URL = process.env.NEXT_PUBLIC_MOCK_API_URL;
export const MOCK_USER_ACCESS_TOKEN = process.env.NEXT_PUBLIC_MOCK_USER_ACCESS_TOKEN;
export const TEKNIX_USER_ACCESS_TOKEN = process.env.NEXT_PUBLIC_TEKNIX_USER_ACCESS_TOKEN;
export const TEKNIX_USER_SESSION_TOKEN = process.env.NEXT_PUBLIC_TEKNIX_USER_SESSION_TOKEN;
export const TEKNIX_MUSIC_URL = process.env.NEXT_PUBLIC_TEKNIX_MUSIC_URL;